Fixes Agent Metric
cyclus/cymetric pull request #175
Opened 2020-11-17 14:07 UTC by abachma2

Attempts to fix the Agents metric, reported in Issue #174, by changing the exit variable read into the function and how the length of the table is determined.

2020-11-17 14:52 UTC, bam241 commented on cymetric/metrics.py
> +    #idx = mergeon.size
I think idx as to be defined as in l245:
`exit_index = ['SimId', 'ExitTime', 'Prototype']`

2020-11-17 21:01 UTC, bam241 commented on cymetric/metrics.py
> +        agent_exit = agent_exit#.reindex(index=idx)
this else statement is not required anymore...

2020-11-17 21:01 UTC, bam241 commented on cymetric/metrics.py
> +        agent_exit = entry[['SimId','AgentId']]
```suggestion
        agent_exit = entry[['SimId','AgentId']].copy()
```
Pandas seems to advices this usage instead.

2020-11-18 17:01 UTC, bam241 commented on cymetric/metrics.py
> +                                        'Exits','ExitTime',how='left',on=mergeon)
```suggestion
                                        'Exits','ExitTime', on=mergeon)
```
this is probably not required.

2020-11-18 17:26 UTC, bam241 requested changes
Looking good!
Great job @abachma2 .
Some few clean-up and I'll be ready to merge !

2020-11-18 17:26 UTC, bam241 commented on cymetric/metrics.py
> +    #df.rename({'Exits':'ExitTime'},axis='columns')
this is not used anymore.

2020-11-18 17:26 UTC, bam241 commented on cymetric/metrics.py
> +    idx = ['SimId','AgentId','ExitTime']
I believe the idx isn't use...

2020-11-18 17:28 UTC, bam241 commented on cymetric/metrics.py
> +                                        'ExitTime','Exits',on=mergeon)
pep8 (our formatting guidelines) recommends space after commas, and there is trailing space at the end of the line.

2020-11-18 17:30 UTC, bam241 commented on cymetric/metrics.py
> +                                        'ExitTime','Exits',on=mergeon)
* pep8 is not our guideline but the one we try to follow :)

2020-11-18 17:33 UTC, bam241 reviewed
you missed 4 missing spaces. (I added them as suggestions)

2020-11-18 17:33 UTC, bam241 commented on cymetric/metrics.py
> +        df = tools.merge_and_fillna_col(df, exit[['SimId','AgentId','Exits']],
```suggestion
        df = tools.merge_and_fillna_col(df, exit[['SimId', 'AgentId', 'Exits']],
```

2020-11-18 17:33 UTC, bam241 commented on cymetric/metrics.py
> +                                        'ExitTime','Exits',on=mergeon)
```suggestion
                                        'ExitTime', 'Exits', on=mergeon)
```

2020-11-18 17:39 UTC, bam241 approved these changes
LGTM! 

Thank a lot @abachma2 for fixing this bug!

I'll merge this by the end of the week if no-one disagree

2020-12-02 17:16 UTC, abachma2 commented
Can this be merged now @bam241?

2020-12-02 17:17 UTC, bam241 commented
yes sorry for the delay!

2020-12-02 17:17 UTC, bam241 commented
Merging ! thx @abachma2 for fixing this !!!

2020-12-02 17:17 UTC, merged